-- MySQL Script generated by MySQL Workbench
-- Sat May 15 19:45:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wealth
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wealth` ;

-- -----------------------------------------------------
-- Schema wealth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wealth` DEFAULT CHARACTER SET utf8 ;
USE `wealth` ;

-- -----------------------------------------------------
-- Table `wealth`.`Security`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wealth`.`Security` ;

CREATE TABLE IF NOT EXISTS `wealth`.`Security` (
  `id_security` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `weight` FLOAT NOT NULL,
  PRIMARY KEY (`id_security`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wealth`.`Security_price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wealth`.`Security_price` ;

CREATE TABLE IF NOT EXISTS `wealth`.`Security_price` (
  `id_security_price` INT NOT NULL AUTO_INCREMENT,
  `id_security` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_security_price`),
  INDEX `id_security_fk_idx` (`id_security` ASC) VISIBLE,
  CONSTRAINT `id_security_fk`
    FOREIGN KEY (`id_security`)
    REFERENCES `wealth`.`Security` (`id_security`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
